### ISSUE TITLE
HyperRef from the code example does not exist in the module

### ISSUE THREAD

**Issue by xeno-john** [jtc42/fastapi-hypermodel#3]
https://github.com/jtc42/fastapi-hypermodel/blob/main/examples/simple_app.py
as described at this link, there should be a HyperRef to import from the fastapi_hypermodel module.

The provided example cannot work with that object missing and the examples are not updated. 

Can these examples be updated or can someone give me an insight on how to use this module to create links when accessing resources?

**Comment by jtc42** [comment]
Hey, thanks for flagging this! I must have forgotten to update the example file.

If you check the example now, I've fixed the bad import, added some extra examples (e.g. the `LinkSet` class), and added some comments.

https://github.com/jtc42/fastapi-hypermodel/blob/main/examples/simple_app.py

Hopefully that's an improvement, but if you still have issues let me know. Proper docs are on the todo list as soon as I get chance. It's a simple library so really shouldn't be taking me long....

**Comment by xeno-john** [comment]
Hey there! 
The links seem to not be generated whenever I create a model entity with the `from_orm` method.
I'm not sure if I understood how to use this module properly.

```
class Book(BaseModel):
    isbn: str
    title: str
    publisher: str
    year_of_publishing: int
    genre: str

    links = LinkSet(
        {
            "self": UrlFor("get_book", {"isbn": "<isbn>"}),
            "books": UrlFor("get_books"),
        }
    )

    class Config:
        orm_mode = True
        
[..] 
response_body = Book.from_orm(db_response.payload)
json_data = jsonable_encoder(response_body.__dict__)
return JSONResponse(content=json_data, status_code=status_code)
```

Response would be:

```
{
    "isbn": "1232914851245",
    "title": "STR",
    "publisher": "STR",
    "year_of_publishing": 2009,
    "genre": "str",
    "links": {
        "self": "",
        "books": ""
    }
}
```

**Comment by jtc42** [comment]
Interesting. In your FastAPI route function, are you populating the `response_model` argument?

I'm obviously missing some context here, but I'm curious why you're calling 

```python
json_data = jsonable_encoder(response_body.__dict__)
return JSONResponse(content=json_data, status_code=status_code)
```
Rather than just returning `Book.from_orm(db_response.payload)` and using FastAPI `response_model` to JSON-ify the response?

**Comment by jtc42** [comment]
Something like this?

```python
[...]
from fastapi import Response, status
[...]

@router.get("/book/{isbn}", response_model=Book)
def book_list( isbn: str, response: Response ):
    db_response = [...]
    status_code = [...]

    response.status_code = status_code

    return db_response.payload
```

**Comment by xeno-john** [comment]
Rewrote the code like this:

@app.get("/api/bookcollection/books/{isbn}", status_code=status.HTTP_200_OK, response_model=Book)
```
def get_book(isbn: str, response : Response):
    """
    Method that handles a DELETE request for a book by the ISBN code.
    """
    db_response = get_book_by_isbn(str(isbn))
    response_body = ''
    if db_response.error:
        status_code = status.HTTP_500_INTERNAL_SERVER_ERROR
        response_body = ErrorDto(status_code, str(db_response.error), 'EXCEPTION')
    elif not db_response.completed_operation:
        status_code = status.HTTP_404_NOT_FOUND
        response_body = BOOK_NOT_FOUND_BODY
    else:
        status_code = status.HTTP_200_OK
        response_body = Book.from_orm(db_response.payload)

    response.status_code = status_code
    return response_body
```

I'm aware currently the method is flawed because of those errorDto assignments, but still, when I call this method through postman I receive the following body:
```
{
    "isbn": "9780511623585",
    "title": "Principia Mathematica",
    "publisher": "Whitehead",
    "year_of_publishing": 1910,
    "genre": "Science",
    "links": {
        "self": "",
        "books": ""
    }
}
```

These talks are unrelated to this open issue, I'm sorry for the spam but I'm not aware how to get the links working.

**Comment by jtc42** [comment]
I just wrote out a massive long comment going through a bunch of debug steps before I realised...

Replace
```python
class Book(BaseModel):
    [...]
```
with
```python
class Book(HyperModel):
    [...]
```

**Comment by xeno-john** [comment]
That indeed seems to have solved it.
Thanks a lot, Joel.

```json
{
    "isbn": "9780511623585",
    "title": "Principia Mathematica",
    "publisher": "Whitehead",
    "year_of_publishing": 1910,
    "genre": "Science",
    "links": {
        "self": "/api/bookcollection/books/9780511623585",
        "books": "/api/bookcollection/books/"
    }
}
```

**Comment by jtc42** [comment]
Honestly no problem, glad it turned out to be a simple fix. Good luck with the project!
